### ISSUE TITLE
Report TLS use in delivery logs

### ISSUE THREAD

**Issue by tommairs** [KumoCorp/kumomta#73] opened 2023-07-24 21:01 UTC
### What Operating System are you seeing this problem on?

CBL-Mariner/Linux"

### What Hardware is this system running?

Azure standard VM

### KumoMTA version

kumod 2023.07.22-d4ae999a

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version that I tried

### Describe the bug

The logs seem to be lacking a field to show if TLS was used during the transmission.
I would expect to be able to include a TLS field in logs to report a boolean ( used or not used) .

IE: "tls":"1"

### Configuration

This could either be configured as meta data or as a standard logging field

**Comment by wez** [comment] 2023-08-05 13:35
Duplicate of https://github.com/KumoCorp/kumomta/issues/39, I think.

**Closed by wez** 2023-08-05 13:35 UTC
Labels: enhancement
